from .UnionQuiz import UnionQuiz
from .McStasScriptQuiz import McStasScriptQuiz
from .McStasScriptDiagnosticsQuiz import DiagnosticsQuiz
from .UnionSubQuiz1Materials import UnionSubQuiz1Materials
from .UnionSubQuiz2Geometry import UnionSubQuiz2Geometry
from .UnionSubQuiz3Concepts import UnionSubQuiz3Concepts